---
- name: Create defaut Groups
  group:
    name: "{{ item.name }}"
    gid: "{{ item.uid }}"
    state: present
  become: yes
  with_items:
    - "{{ admin_users }}"
    - { name: "sudo-nopwd", uid: "1199" }

- name: Set sudo-nopwd-settings in sudoers-file
  lineinfile:
    path: /etc/sudoers
    regexp: '^%sudo-nopwd '
    insertafter: '^%sudo'
    line: '%sudo-nopwd ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'
  become: yes

- name: Create defaut User
  ansible.builtin.user:
    name:     "{{ item.name }}"
    comment:  "{{ item.full_name }}"
    group:    "{{ item.name }}"
    groups:   "{{ item.groups }}"
    password: "{{ item.password }}"
    uid:      "{{ item.uid }}"
    shell:    "{{ item.shell }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    ssh_key_comment: "{{ item.name }}@{{ inventory_hostname }}"
    state: present
    append: yes
  become: yes
  with_items:
    - "{{ admin_users }}"

- name: Set SSH-Key for default Admin User
  authorized_key:
    user: "{{ item.user }}"
    key: "{{ item.key }}"
    state: present
  become: yes
  with_items:
    - "{{ ssh_keys }}"

- name: Copy .vimrc
  copy:
    src: "vim/vimrc"
    dest: "/home/{{ item.name }}/.vimrc"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: '0644'
  become: yes
  with_items:
    - "{{ admin_users }}"

- name: Create bin-directory
  file:
    path: "/home/{{ item.name }}/bin"
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: 0755
  become: yes
  with_items:
    - "{{ admin_users }}"

- name: Create etc-directory
  file:
    path: "/home/{{ item.name }}/etc"
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: 0755
  become: yes
  with_items:
    - "{{ admin_users }}"

- name: Copy system_status.sh
  copy:
    src: "system_status.sh"
    dest: "/home/{{ item.name }}/bin/system_status.sh"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: '0744'
  become: yes
  with_items:
    - "{{ admin_users }}"

- name: Generiere Filetransfer-File
  template:
    src: "filetransfer_source.cfg.j2"
    dest: "/home/{{ item.name }}/etc/filetransfer_source.cfg"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: '0600'
  become: yes
  with_items:
    - "{{ admin_users }}"

- name: Update .bashrc with system_status.sh
  lineinfile:
    dest: "/home/{{ item.name }}/.bashrc"
    line: 'if [ -f ~/bin/system_status.sh ]; then ~/bin/system_status.sh; fi'
    insertafter: "EOF"
    state: present
  become: yes
  with_items:
    - "{{ admin_users }}"

